version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8  # Adjust the Python version as needed
    commands:
      - echo "Installing system dependencies"
      - apt-get update -y
      - apt-get install -y python3-dev python3-pip
  pre_build:
    commands:
      - echo "Installing project dependencies"
      - pip install -r requirements.txt
      - pip install django

  build:
    commands:
      - echo "Running tests"
      # Add any other testing commands you need
      # Add any other testing commands you need

artifacts:
  files:
    - '**/*'
# Change this path to the desired location for the build artifacts
# Change this path to the desired location for the build artifacts