version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # Adjust the Python version as needed
    commands:
      - echo "Installing system dependencies"
      - apt-get update -y
      - apt-get install -y python3-dev python3-pip

  pre_build:
    commands:
      - echo "Installing project dependencies"
      - pip install -r requirements.txt
      - pip install django
      - python manage.py collectstatic --noinput

  build:
    commands:
      - echo "Running tests"
      - python manage.py test  # Add any other testing commands you need

artifacts:
  files:
    - '**/*'
  name: my-django-app-build-${CODEBUILD_BUILD_ID}
  path: /tmp/build-artifacts  # Change this path to the desired location for the build artifacts
